### ISSUE TITLE
The __version__ string in current release of libraries is incorrect semver.

### ISSUE THREAD

**Issue by ntoll** [adafruit/Adafruit_CircuitPython_binascii#2]
Just a quick note: while I notice the `__version__` object in the module, as it is in current master, is correct semver, this isn't the case in the copy of this module that's currently distributed (the associated value is `"v1.0"`).

I'm just highlighting this as a courtesy since this mucks up the ability of `circup` to work with the module. I'm pretty certain the next release will have the fixed version, but flagging just in case there's something which automagically updates this value to the wrong thing.

Thanks!

cc/@ladyada

**Comment by ladyada** [comment]
@brentru plz take a look & bump/fix!

**Comment by brentru** [comment]
@ntoll  Latest release uses the correct semver, bumped to `1.0.1`
(https://github.com/adafruit/Adafruit_CircuitPython_binascii/releases/tag/1.0.1).
